### ISSUE TITLE
Qualifikationsstatus wird falsch angezeigt (Schulungen nicht erkannt)

### ISSUE THREAD

**Issue by HannahRLCC** [fabianzwodrei/lc-app#7]
Bei mehreren Mitgliedern wird der Status "Vollqualifiziert" nicht angezeigt, obwohl genügend gültige Schulungen vorliegen.

**Comment by fabianzwodrei** [comment]
Bitte schreibe mir ein paar Ids von Mitgliedern damit ich das testen kann

**Comment by fabianzwodrei** [comment]
Aktuell ist das System so eingestellt, dass es eine Schulung aus "Aktuelle Gesetzgebung" und zwei Schulungen _nicht_ aus Aktuelle Gesetzgebung erwartet um VQ zu zeigen.

**Comment by HannahRLCC** [comment]
Verstehe. Kann man das ändern, dass zwei beliebige weitere Schulungen erforderlich sind - so steht es in unserer Ausbildungsordnung ("mindestens eine der drei gültigen Schulungen muss aus "Aktuelle Gesetzgebung" sein")?

**Comment by fabianzwodrei** [comment]
erledigt
