### ISSUE TITLE
Status Vollqualifiziert

### ISSUE THREAD

**Issue by HannahRLCC** [fabianzwodrei/lc-app#8]
Mir ist leider noch eine kleine Sache im Intranet aufgefallen. Und zwar ist im Intrant für den Status als Vollqualifziert die Teilnahme am Mandatsworkshop keine Voraussetzung. Dies sollte sie aber sein, da ein Mitglied nur dann vollqualifiziert ist, wenn es daran teilgenommen hat - sonst könnte es auch vollqualifiziert sein, obwohl es nicht qualifziertes Mitglied ist, was ja wenig Sinn ergibt... (siehe Bild)
![Intranet](https://user-images.githubusercontent.com/47562311/54686963-c356f680-4b1a-11e9-9da2-e58a5e511390.JPG)

Es müsste also als Voraussetzung für "Vollqualifziert" noch der Mandatsworkshop hinzugefügt werden, der aber zugleich solange er gültig ist als eine der drei erforderlichen Schulungen zählt - geht das?

**Comment by fabianzwodrei** [comment]
also so:?

<img width="697" alt="Screen Shot 2019-03-26 at 11 44 00" src="https://user-images.githubusercontent.com/809454/54991141-95f7c600-4fbc-11e9-8216-9c08b59a85be.png">

**Comment by fabianzwodrei** [comment]
tatsächlich mandatsarbeit doppelt verwenden?

**Comment by HannahRLCC** [comment]
Ja genau

**Comment by fabianzwodrei** [comment]
wird gemacht 👍

**Comment by HannahRLCC** [comment]
Perfekt, danke

**Comment by fabianzwodrei** [comment]
ist installiert. Danke fürs Testen
